import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { InferGetServerSidePropsType } from "next";
// import SignIn from "@/features/auth/SIngIn";
import SignIn from "@/components/SignIn";

const inter = Inter({ subsets: ["latin"] });

type Data = {
  data: string;
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SignIn />
    </>
  );
}
